# Generated by Django 5.1.2 on 2024-11-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#F1C40F', 'Yellow'), ('#9B59B6', 'Purple'), ('#1ABC9C', 'Teal'), ('#E74C3C', 'Coral'), ('#34495E', 'Gray'), ('#2ECC71', 'Lime'), ('#3498DB', 'Sky Blue')], max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#F1C40F', 'Yellow'), ('#9B59B6', 'Purple'), ('#1ABC9C', 'Teal'), ('#E74C3C', 'Coral'), ('#34495E', 'Gray'), ('#2ECC71', 'Lime'), ('#3498DB', 'Sky Blue')], max_length=7),
        ),
    ]
