# Generated by Django 5.1.2 on 2024-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_event_user_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
