# Generated by Django 5.1.2 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_event_endofrepeat_event_repeat_alter_event_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('Never', 'Never'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Never', max_length=10),
        ),
    ]
