# Generated by Django 5.1.2 on 2024-11-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
