# Generated by Django 5.1.2 on 2024-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_event_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
