# Generated by Django 5.1.2 on 2024-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
