# Generated by Django 5.1.2 on 2024-11-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_tokenmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenManager',
        ),
    ]
