# Generated by Django 5.1.2 on 2024-11-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_delete_tokenmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='AuthToken',
        ),
    ]
