# Generated by Django 5.1.2 on 2024-11-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_rename_token_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
